### ISSUE TITLE
The process of downloading will always interrupt the data, can provide a different download address for download? Thank you

### ISSUE THREAD

**Issue by GreatJiweix** [nikitalpopov/vedai#1]
The process of downloading will always interrupt the data, can provide a different download address for download? Thank you

**Comment by nikitalpopov** [comment]
Sorry for ignoring you for so long.
If you select 'Download zip' option, then maybe you're right.  
![Download zip](https://i.gyazo.com/cb220379de957c0f6b4b2e703a17aecc.png)

But `git clone` should handle it for you since it does checksum match (correct me if I'm wrong).

> Git stores snapshots not patches. Internally, Git runs SHA checksum on every file. Every commit is just a list of file names and their corresponding checksums. The database mapping checksum to its content is shared among commits. If the content of a file in two commits are the same, only the checksum needs to be stored in the two commits. If the file is modified, a new mapping of checksum to the modified file is created and stored.

[Source](http://wittawat.com/posts/git-summary.html)

**Comment by nikitalpopov** [comment]
Few more details [there](https://stackoverflow.com/questions/50650364/when-does-git-actually-verify-the-integrity-of-the-commit-chain/50651137?noredirect=1#comment115379452_50651137)

> Everything in Git is stored as an "object". Each object has a hash ID, which we compute using some sort of checksum (SHA-1 currently but Git 2.29 already has prototype support for other hash algorithms). Git doesn't store files, just these objects. The extraction code must be told the hash ID, because that's how we look up an object in the key-value database that stores them. The extraction code then computes the hash again during extraction. This must match the key used to look up the object. If it does, the object is not corrupted.

> The actual re-checking of object hash IDs during git clone is slightly deferred, but this is an implementation detail: git clone consists of six steps, the fifth step being a git fetch that obtains all reachable objects. The sender can send those objects one at a time, in which case they'd get checked as they go into storage, but that's terribly slow, so modern protocols send a so-called pack file with delta-compressed objects in it. The receiving Git then runs a pack indexer, which reads and checks all the objects. Hence clone finds any errors during the indexing.
