### ISSUE TITLE
Find some trouble in the txt files

### ISSUE THREAD

**Issue by QingxinWx** [nikitalpopov/vedai#2]
Hi，when I download the data，I find some trouble in the txt files，the ID are 341 365 369 411 ，please check them ， thanks

**Comment by thaodod** [comment]
This repo is already the converted dataset!. I checked the annotations. no your mentioned IDs existed!

**Comment by nikitalpopov** [comment]
@QingxinWx @doduythao should I close this?

**Comment by thaodod** [comment]
yes

**Comment by nikitalpopov** [comment]
@doduythao cool, thanks!
